# -*- mode: ruby -*-
# Minimal Brewfile for Falkor's dotfile installation --
# see https://github.com/Falkor/dotfiles

# Pre-configuration for brew sources
tap "buo/cask-upgrade"

# Couple of mandatory applications
brew 'readline'
brew 'bash'
brew 'bash-completion'
brew 'coreutils'
brew 'ctags-exuberant'
brew 'curl'
brew 'git'
brew "git-delta"
brew "git-extras"
#brew "git-flow-avh"
brew 'lua'
brew 'mas'
brew 'sqlite'
brew 'python'
brew "powerlevel10k"
brew 'terminal-notifier'
brew 'tig'
brew 'vim'
brew 'wget'


# completions
brew 'bash-completion'
brew 'brew-cask-completion'
brew 'zsh-completions'

# Mac GUIs Apps
cask "iterm2"

# Mac Store Apps
#mas "Xcode", id: 497799835
#mas 'Slack', id: 803453959

# Special fonts
cask 'font-source-code-pro-for-powerline'
cask 'font-hack-nerd-font'
